### ISSUE TITLE
bring `sandwich`, `meat` into RItools?

### ISSUE THREAD

**Issue by benthestatistician** [josherrickson/pbph#7]
@josherrickson , could I interest you in bringing your cluster-aware sandwich functions into RItools?  We could make use of them for various purposes over there. 

A couple things I'd suggest doing in the process:
1. How about enabling the `adjust=` argument with a non-null `cluster=` argument also?  (Maybe while changing `adjust=` to default to `TRUE`.)
2. the adjustment factor is non-obvious.  Is there a citation you could put for it?  If so I'd recommend adding it to the docs for meat.
3. I'm a little uncomfortable with exporting functions bearing the same name as functions in the sandwich package itself.  Perhaps the package could export aliases of the two functions, eg "sandwich_clus" & "meat_clus", or "sandwichc"/"meatc"?
4. Add yourself as author of the two functions.

**Comment by josherrickson** [comment]
1. `adjust=FALSE` is a default argument to `sandwich`. The only tweaks I did there were forcing it to `TRUE` when clusters were given, and adjusted from `n/(n - k)` to `m/(m - 1) * (n - 1)/(n - k)`, which collapses to the first case in the absence of clusters.
2. I have a citation in the paper for that adjustment, I'll move it over.
3. Overall my intention was to mimic the functionality in [lmerTest](https://cran.r-project.org/web/packages/lmerTest/index.html); if you're not familiar, it overloads `lmer` so that running pre-existing code enables the hypothesis testing. `pbph` (should) correctly load `sandwich` prior, so that users can't load them in the wrong order. 

Your comments about name & `adjust` suggest that you'd prefer I deviate from `sandwich`'s implementation?

**Comment by benthestatistician** [comment]
1. I now see your rationale for having `adjust=` default to `TRUE`.  My concerns are that (i) the user currently has no way to turn the adjustment off; and (ii) as it stands, if the user specified `adjust=FALSE` then that preference would be quietly ignored.  
2. good, thanks.
3. thanks for clarifying that; I wasn't aware of the `lmerTest` precedent.  I still have the concern that if the user somehow loaded things in the incorrect order then any cluster= argument that she provided to `sandwich` or `meat` would be (i) ignored and (ii) quietly so.

**Comment by benthestatistician** [comment]
I just heard about 2 existing packages for cluster-robust SEs:  https://github.com/kolesarm/Robust-Small-Sample-Standard-Errors, and the clubSandwich package https://github.com/jepusto/clubSandwich .  On a quick review `clubSandwich` comes off quite well. I also know the author, at least a little, as does Adam Sales.

**Comment by josherrickson** [comment]
1) Fair enough, I'll think through this further at some point.

3) I'm pretty confident that since `sandwich` is a dependency in `pbph`, you cannot have `sandwich::sandwich` masking `pbph::sandwich`. E.g.

```
> unloadNamespace("sandwich")
Error: package ‘sandwich’ is required by ‘pbph’ so will not be detached
```

I could add a check in `pbph` (something like `if(which(grepl("pbph", search())) > which(grepl("sandwich", search())))`) to warn if `sandwich` is higher on the search stack, but it won't address someone calling `sandwich` or `meat` directly, which you are right, would silently error. (Though, again, I don't think that's possible.)

`clubSandwich` does seem promising, albeit vastly under-documented. Do you know if there's a paper attached to it? For the record, `type=CR1S` is the adjustment method I was using. 

```
> sandwich(mod, cluster = d$c)
            (Intercept)           x
(Intercept)  0.07611570 -0.04358431
x           -0.04358431  0.30099406
> vcovCR(mod, d$c, type = "CR1S")
            (Intercept)           x
(Intercept)  0.07611570 -0.04358431
x           -0.04358431  0.30099406
```

Does the existence of `clubSandwich` mean that you don't want me to move my versions over to RItools right now? I might in the future consider using `clubSandwich` in `pbph`, but that's a project for later.

**Comment by benthestatistician** [comment]
1) OK great.  Happy to discuss, too, if you like. 

3) I see now that for `pbph` purposes, i.e. the purposes for which it was intended, you've anticipated and gotten ahead of the name masking issue.  (Nice.)

4) Yes, let's hold off on putting this into `RItools`.  In that context there would be a risk of inadvertent masking, and given the existence of a further-along package in the general direction that this would have stepped toward, I think it's best to hold off.   Again, happy to discuss; but i'll take the liberty of closing out this issue.
